services:
  # Web App (Node.js Express)
  web:
    build: ./web-app-express
    container_name: unimq_web
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./web-app-express/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network

  # Database (MariaDB)
  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: unimq
      MYSQL_USER: user_app
      MYSQL_PASSWORD: password_app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_admin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - app-network

  # Background Worker (Node.js) for MQTT Log System
  mqtt-worker:
    build: ./mqtt-worker
    container_name: mqtt_background_worker
    restart: always
    env_file:
      - ./web-app-express/.env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
